---
title: "Pokemon"
author: "Téllez Gerardo Rubén"
date: "18/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(reticulate)

#use_python("/Users/ruben/anaconda3/python.exe")

#si está instalado en un disco duro externo a veces da error.
```

## Pokemon de Py a R


```{python}
import pandas as pd

pokemon = pd.read_csv("pokemon.csv")

print(pokemon.head())
print(pokemon.shape)

pokemon = pokemon[pokemon["Generation"]==1]
pokemon = pokemon[["Type 1","Type 2", "Speed"]]

print(pokemon.shape)
pokemon = pokemon.dropna()
print(pokemon.shape)
```


## Transmisión de los datos de Python a R

```{r, fig.width=7, fig.height=4}
hist(py$pokemon[, "Speed"], breaks = 10, main="Velocidad de los Pokemon")
```


## Pokemon de R a Py

```{r}
library(tidyverse)
pokemon2 = read.csv("pokemon.csv", header = TRUE)


pokemon2 <- pokemon2 %>%
  filter(Generation==1) %>%
  select(Type.1, Type.2, Speed) %>%
  na.omit()
summary(pokemon2)



```


## Transmisión de datos de R a Python

```{python}
print(r.pokemon2.head())
```

















