---
title: "Estudio de datos cuantitativos"
author: "Téllez Gerardo Rubén"
date: "15/12/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Descripción de datos cuantitativos

## Datos cuantitativos

Los _datos cuantitativos_ son los que se expresan en cantidades que se representan mediante números. Éstos se suelen clasificar en _continuos_ y _discetos_.

+ Los _datos continuos_ son los que, si existiese la posibilidad de medirlos con precisión infinita, en principio podríamos tomar todos los valores de un intervalo de la recta real. A modo de ejemplo, el peso, la altura, el tiempo... son datos de ese tipo.
+ Por su parte, los _datos discretos_ son los que pueden tomar un solo conjunto contable de valores. El número de colores de un gato, el número de individuos que conforman una población son algunos ejemplos de ejemplos de este tipo de datos.

## Datos cuantitativos

Conviene tener en cuenta que esta división que este división es solo teórica. Es decir, en la práctica, todos estos datos son discretos puesto que la precisión infinita no existe. Sin embargo, es necesario de vez en cuando suponer los datos de tipo continuo para así poder utilizar técnicas específicas en su análisis.

## Datos cuantitativos

A la hora de estudiar _factores cuantitativos_, podemos usar las frecuencias que hemos visto hasta el momento: absolutoa, relativa, acumulada y relativa acumulada. Esti se debe a que podemos ordenar los datos cuantitativos en el orden natural de los números reales.

En este caso, disponemos de muchas otras técnicas descriptivas aparte de las frecuencias, puesto que estamos trabajando con números reales podemos operar con ellos.

Los datos cuantitativos admiten 2 tipos de tratamiento según trabajemos con los _row data_ (datos originales) o bien los agrupemos en clases o intervalos.

En esta lección trabajaremos sobre la primera situación. En la siguiente, estudiaremos la descripción de datos cuantitativos agrupados.










