---
title: "Reticulate"
author: "Téllez Gerardo Rubén"
date: "10/3/2021"
output: pdf_document
---

## Librería

Para listar directorios, con el python de anaconda

```{r}
library(reticulate)
use_python("/Users/ruben/anaconda3/")
os <- import('os')
os$listdir(".")
```
Importar fichero python

```{r}
source_python("script_ejemplo.py")
duplicar(23)
```

Importar clases
```{r, }
#py_run_file()
```

No convertir objetos Py a R, trabajar con nativos Py
```{r}
np <- import("numpy", convert = FALSE)
x <- np$array(c(1:4))
sum <- x$cumsum()

print(sum)
```

Convertir Py a R
```{r}
py_to_r(sum)
```

## Ayuda de una función py
```{r}
py_help(list())
```

## Arrays
```{r}
a <- np_array(c(1:10), order="C")
a
```
```{python}
print("Hello word")
```

```{r}
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```
```{python}
import numpy as np
import pandas as pd

r.datos_py
```

## Sparse Matrix
```{r}
library(Matrix)
N = 6
set.seed(123)
  i = sample(N, N, replace = F)
  j = sample(N, N, replace = F)
  x = runif(N)
  dims = c(N, N)
matrizSparse <- sparseMatrix(
  i=i,
  j=j,
  x=x,
  dims= c(N,N)
)
matrizSparse

```
## Convertir datos de R a Py
```{r}
library(magic)
magia <- magic(6)
magia
magia_py <- r_to_py(magia)
```



```{python}
r.magia_py
```
```{r}
py_to_r(magia_py)
```

