---
title: 'Tarea 3: Estructuras de datos.'
author: "Resuelto por Rubén Téllez Gerardo"
date: "5/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 1

Da la entrada (2,2) de $A \cdot (A+A) \cdot A$, con
$$A = \begin{pmatrix} 1 & 3 \\  2 & 4 \end{pmatrix}$$

```{r}
A = matrix(1:4, nrow = 2)

#Entrada 2,2:
A[2, 2]
```

## Ejercicio 2
Da los valores propios de la matríz
$$B = \begin{pmatrix} 2 & 4 & -6 \\ 0 & 0 & 3 \\ 0 & -2 & 5 \end{pmatrix}$$

```{r}
B <- matrix(c(2, 0, 0, 4, 0, -2, -6, 3, 5), nrow = 3)
eigen(B)$values
```

## Ejercicio 3
Da, redondeando a 3 cifras decimales, los vectores propios de la matriz
$$C = \begin{pmatrix} -48 & 35 & -12 \\ -134 & 95 & -32 \\ -194 & 133 & -44 \end{pmatrix}$$

```{r}
C <- matrix(c(-48, 35, -12, -134, 95, -32, -194, 133, -44), nrow = 3, byrow = TRUE)

round(eigen(C)$vectors, 3)
```

## Ejercicio 4
Da el rango de la matriz
$$D = \begin{pmatrix} -2 & -8 & -2 &3 \\ -3 & -6 & -1 & 2 \\ -9 & -22 & -3 &7 \\ -18 & -44 & -8 & 15 \end{pmatrix}$$

```{r}
D = matrix(c(-2, -3, -9, -18, -8, -6, -22, -44, -2, -1, -3, -8, 3, 2, 7, 15), nrow = 4)

qr(D)$rank
```






